### ISSUE TITLE
How can i buy you a coffee?

### ISSUE THREAD

**Issue by foreversun69** [jasonmotylinski/hierarchical-outgoing-links#10]
Hello sir,

this is a really very good plugin! Many thanks for it! How can I buy you a coffee?

With kind regards
foreversun

**Comment by jasonmotylinski** [comment]
I appreciate the sentiment and I'm glad you like the plugin! I've added a link to buy me a coffee to the README.

**Comment by foreversun69** [comment]
I would love to support you, but I don't have a credit card, can you please do paypal?

Thank you very much for your commitment.

**Comment by jasonmotylinski** [comment]
Unfortunately not, I just accept via Buy Me a Coffee.
