### ISSUE TITLE
Remove unnecessary call to getFirstLinkpathDest function

### ISSUE THREAD

**Issue by jmotylinski-gcmlp** [jasonmotylinski/hierarchical-outgoing-links#8]
https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/4f333f69ff2e9d2d04ab3da5a84477a830341486/src/view.ts#L74

The const isn't referenced and is unnecessary. Removing the line should also increase performance.

**Comment by jasonmotylinski** [comment]
removed unnecessary call
