### ISSUE TITLE
[FR] Add an option to hide attachments

### ISSUE THREAD

**Issue by Moyf** [jasonmotylinski/hierarchical-outgoing-links#9]
Hey, it's a very useful plugin, thanks for developing!

Could you please add an option to hide the images or other attachments, so that we can focus on the Notes only ?

**Comment by Moyf** [comment]
> I like the idea! I'm considering adding a filter option to the plugin settings page. It would allow a basic regular expression so that you could pick and choose what you want to filter out. Would that work?

Yeah I believe it is achievable!

**Comment by jasonmotylinski** [comment]
Added settings for excluding files based on a regular expression. Released in version 1.0.18

**Comment by Moyf** [comment]
> Added settings for excluding files based on a regular expression. Released in version 1.0.18

Really appreciate it, thank you!  🥳
